create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text not null check (char_length(phone) between 7 and 24),
  email text,
  status text not null default 'potential' check (status in ('potential', 'active', 'inactive', 'vip')),
  notes text not null default '',
  last_contacted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists customers_phone_unique on public.customers (phone);
create index if not exists customers_status_idx on public.customers (status);
create index if not exists customers_created_at_idx on public.customers (created_at desc);

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text,
  email text,
  subject text not null default '',
  message text not null check (char_length(message) between 2 and 5000),
  status text not null default 'new' check (status in ('new', 'contacted', 'resolved', 'spam')),
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (coalesce(nullif(phone, ''), nullif(email, '')) is not null)
);

create index if not exists contact_requests_status_idx on public.contact_requests (status);
create index if not exists contact_requests_created_at_idx on public.contact_requests (created_at desc);

alter table public.journal_articles
  add column if not exists slug_vi text,
  add column if not exists slug_en text,
  add column if not exists excerpt_vi text not null default '',
  add column if not exists excerpt_en text not null default '',
  add column if not exists content_vi text not null default '',
  add column if not exists content_en text not null default '',
  add column if not exists created_at timestamptz not null default now();

update public.journal_articles
set
  slug_vi = coalesce(slug_vi, case id
    when 1 then 'lam-sach-sau-hay-phuc-hoi-da'
    when 2 then 'thu-gian-dau-vai-gay'
    when 3 then 'duong-net-guong-mat-tu-nhien'
    when 4 then 'chuan-bi-lieu-trinh-cong-nghe-cao'
    when 5 then 'cham-soc-da-sau-lieu-trinh'
    when 6 then 'tai-tao-be-mat-da'
    else 'bai-viet-' || id::text end),
  slug_en = coalesce(slug_en, case id
    when 1 then 'deep-cleansing-or-skin-recovery'
    when 2 then 'relax-scalp-neck-and-shoulders'
    when 3 then 'natural-facial-shape'
    when 4 then 'prepare-for-advanced-treatment'
    when 5 then 'skin-aftercare'
    when 6 then 'refresh-skin-surface'
    else 'article-' || id::text end);

alter table public.journal_articles alter column slug_vi set not null;
alter table public.journal_articles alter column slug_en set not null;
create unique index if not exists journal_articles_slug_vi_unique on public.journal_articles (slug_vi);
create unique index if not exists journal_articles_slug_en_unique on public.journal_articles (slug_en);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at before update on public.admin_users
for each row execute function public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists contact_requests_set_updated_at on public.contact_requests;
create trigger contact_requests_set_updated_at before update on public.contact_requests
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.customers enable row level security;
alter table public.contact_requests enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.customers from anon, authenticated;
revoke all on table public.contact_requests from anon, authenticated;
grant select, insert, update, delete on table public.admin_users to service_role;
grant select, insert, update, delete on table public.customers to service_role;
grant select, insert, update, delete on table public.contact_requests to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.admin_users is 'Server-side allowlist for the Hato Beauty admin dashboard.';
comment on table public.customers is 'Customer relationship records; accessible only through authenticated server APIs.';
comment on table public.contact_requests is 'Website and manual contact requests; accessible only through authenticated server APIs.';
